# -*- coding: utf-8 -*-
"""exercicio3_fila_reversao

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knX5CwgCRQLYDMenHBBlVv9Nx-9WFc8b
"""
class queue:
    def __init__(self):
        self.items = [ ]

    def isEmpty(self):
        return len(self.items) == 0

    def enqueue(self, item):
        self.items.append(item)

    def dequeue(self):
        if not self.isEmpty():
            return self.items.pop(0)
        else:
            return "A fila está vazia."
    def reverse(self):
        stack = [ ]
        while not self.isEmpty():
            stack.append(self.dequeue())
        while stack:
            self.enqueue(stack.pop())

queue = queue()
queue.enqueue(1)
queue.enqueue(2)
queue.enqueue(3)
queue.reverse()
print(f"Fila ao contrário: {list(queue.items)}")
