# -*- coding: utf-8 -*-
"""exercicio1_inversao_string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knX5CwgCRQLYDMenHBBlVv9Nx-9WFc8b
"""

def inverter_string(pilha):
    stack = []

    for char in pilha:
        stack.append(char)

    invertida = ""
    while stack:
        invertida += stack.pop()

    print(invertida)


inverter_string("Hello")
