# -*- coding: utf-8 -*-
"""exercicio4_arvore_pre_ordem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knX5CwgCRQLYDMenHBBlVv9Nx-9WFc8b
"""
class BinaryTree:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

    def insert(self, value):
        if value < self.value:
            if self.left is None:
                self.left = BinaryTree(value)
            else:
                self.left.insert(value)
        else:
            if self.right is None:
                self.right = BinaryTree(value)
            else:
                self.right.insert(value)

    def pre_order(self):
        print(self.value, end=" ")
        if self.left:
            self.left.pre_order()
        if self.right:
            self.right.pre_order()



tree = BinaryTree(8)
tree.insert(8)
tree.insert(12)
tree.insert(5)
tree.insert(1)
tree.insert(19)
tree.pre_order()
